name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-bun
      - run: bun lint
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-bun
      - run: bun typecheck
  build:
    name: build-${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - name: macos-arm
            runs-on: macos-latest
            target: darwin-arm64
          - name: linux-x64
            runs-on: ubuntu-latest
            target: linux-x64
          - name: linux-arm
            runs-on: ubuntu-24.04-arm
            target: linux-arm64
          - name: windows-x64
            runs-on: windows-latest
            target: windows-x64
          # https://github.com/oven-sh/setup-bun/issues/130
          # - name: windows-arm
          #   runs-on: windows-11-arm
          #   target: windows-arm64
    steps:
      - uses: ./.github/actions/setup-bun
      - run: bun build --compile --minify --sourcemap --target=${{ matrix.target }} ./src/index.tsx --outfile dist/ghui-${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghui-${{ matrix.target }}
          path: dist/ghui-${{ matrix.target }}*
